Temp Fix: Navigating between routes was causing an error:
Error {stack: (...), message: "Cannot find module 'null'"}

Presumably caused by loading and unloading of  './icons.js'. More investigation is needed but this fixes the error for default icon usage. Testing is need for custom icons.